# Generated by Django 3.2.8 on 2021-11-06 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('product', '0001_initial'), ('product', '0002_alter_category_id'), ('product', '0003_category_created_at'), ('product', '0004_alter_category_id'), ('product', '0005_alter_category_id'), ('product', '0006_alter_category_id'), ('product', '0007_alter_category_id'), ('product', '0008_alter_category_id'), ('product', '0009_auto_20211016_1533'), ('product', '0010_alter_category_id'), ('product', '0011_alter_category_id'), ('product', '0012_auto_20211016_1732'), ('product', '0013_alter_category_id'), ('product', '0014_imgsrc_product'), ('product', '0015_product_description'), ('product', '0016_auto_20211016_1940'), ('product', '0017_alter_product_primary_image'), ('product', '0018_product_in_stock')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('primary_image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('description', models.TextField(null=True)),
                ('in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='imgSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
