# Generated by Django 3.2.8 on 2021-11-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgsrc',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
