# Generated by Django 3.2.8 on 2021-12-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_imgsrc_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
