# Generated by Django 3.2.8 on 2021-12-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created',
        ),
    ]
