# Generated by Django 3.2.8 on 2021-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsrc',
            name='url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
