# Generated by Django 3.2.8 on 2021-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('testapp', '0001_initial'), ('testapp', '0002_alter_product_name'), ('testapp', '0003_category')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
