# Generated by Django 3.2.8 on 2021-12-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cart', '0001_initial'), ('cart', '0002_cartproduct'), ('cart', '0003_remove_cartproduct_quantity'), ('cart', '0004_cartproduct_quantity'), ('cart', '0005_auto_20211024_1112'), ('cart', '0006_cart_cartproduct'), ('cart', '0007_delete_cartproduct'), ('cart', '0008_cartproduct'), ('cart', '0009_cart_price'), ('cart', '0010_alter_cart_price'), ('cart', '0011_alter_cartproduct_product'), ('cart', '0012_alter_cartproduct_product'), ('cart', '0013_alter_cartproduct_product'), ('cart', '0014_remove_cartproduct_profile')]

    initial = True

    dependencies = [
        ('product', '0018_product_in_stock'),
        ('User', '0003_auto_20211020_1403'),
        ('product', '0006_rename_created_at_category_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
                ('price', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
