# Generated by Django 3.2.8 on 2021-10-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_auto_20211020_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
    ]
