# Generated by Django 3.2.8 on 2021-10-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
