# Generated by Django 3.2.8 on 2021-10-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
