# Generated by Django 3.2.8 on 2021-12-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cartproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='profile',
        ),
    ]
