# Generated by Django 3.2.8 on 2021-12-14 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('User', '0001_initial'), ('User', '0002_auto_20211020_1347'), ('User', '0003_auto_20211020_1403'), ('User', '0004_auto_20211205_1357'), ('User', '0005_alter_profile_phoneno')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=50, null=True)),
                ('phoneno', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
