# Generated by Django 3.2.8 on 2021-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20211020_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneno',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
