# Generated by Django 3.2.8 on 2021-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20211205_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
