# Generated by Django 3.2.8 on 2021-12-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('orders', '0001_initial'), ('orders', '0002_alter_order_status'), ('orders', '0003_auto_20211130_0346'), ('orders', '0004_order_created_at')]

    initial = True

    dependencies = [
        ('product', '0003_alter_product_name'),
        ('User', '0003_auto_20211020_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('total_price', models.PositiveIntegerField(default=0, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
