# Generated by Django 3.2.8 on 2021-11-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING', max_length=200, null=True),
        ),
    ]
